### ISSUE TITLE
Clustergrammar view doesn't fit

### ISSUE THREAD

**Issue by cthoyt** [ComPath/ComPath#68]
There are scroll bars ...

**Comment by ddomingof** [comment]
What was this problem again?

**Comment by ddomingof** [comment]
I dont think we can fix it anyway

**Comment by cthoyt** [comment]
The view tries to guess how big the window is, but it's too big so there are scroll bars. Even if you resize the window, it still has them since it resizes the view

**Comment by ddomingof** [comment]
Wont fix
