### ISSUE TITLE
Mappings can be established both ways

### ISSUE THREAD

**Issue by cthoyt** [ComPath/ComPath#80]
![equivalenc mapping bug](https://user-images.githubusercontent.com/5069736/41362169-facc97c6-6f30-11e8-861c-6de11ecf89a4.png)
On the submit mapping page, if you do the same equivalent mapping but the different order, it says you established a new mapping. This should say " you already established that mapping"

**Comment by ddomingof** [comment]
Oups

**Comment by cthoyt** [comment]
When you're sorting the two entries, it needs to be on the tuple of database, name and not just database in case they are two from the same database

**Comment by ddomingof** [comment]
@cthoyt I think this also work
