### ISSUE TITLE
Improper capitalization in "Pathway Details" page

### ISSUE THREAD

**Issue by cthoyt** [ComPath/ComPath#86]
- KEGG is improperly capitalized in the row labeled "Resource"
- The labels in the list of equivalent pathways

See: https://compath.scai.fraunhofer.de/pathway/kegg/path:hsa04330

<img width="769" alt="screen shot 2018-07-26 at 5 06 50 pm" src="https://user-images.githubusercontent.com/5069736/43270848-4e7912a0-90f6-11e8-95f7-40a5d4fa8fec.png">

**Comment by ddomingof** [comment]
Already fixed after deployment
